### ISSUE TITLE
The symlinks in thirdparty point to something on your local machine

### ISSUE THREAD

**Issue by 343max** [zhuowei/VisionOSStereoScreenshots#1]
The symlinks in the `thirdparty` directory are pointing to a directory on your machine: `/Users/zhuowei/Documents/winprogress/alvr/ALVR`

**Comment by rae** [comment]
The ALVR above is mentioned in the README. The second file in the _alvr_ branch points to `/Volumes/orangehd/docs/repos/x264` - another local directory. Is this referring to https://github.com/mirror/x264 ?

**Comment by zhuowei** [comment]
Added as submodules. (Also added a CI build script. It won't work yet since Github Actions only has Xcode 15 beta 1, which doesn't have the visionOS SDK, but it should work once that's available)
